server:
  address: localhost
  port: 8081

spring:
  thymeleaf:
    encoding: UTF-8
    cache: false
    mode: HTML5
  servlet:
    multipart:
      max-file-size: 1024KB
      max-request-size: 1024KB
  data:
    mongodb:
      uri: mongodb://localhost:27017/blog